spring.application.name=demo

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3308/Proyecto_final
spring.datasource.username=Gabriel
spring.datasource.password=@Udea3nPr0gSQL

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# No modificar las tablas existentes
spring.jpa.hibernate.ddl-auto=none

# Mostrar el SQL en consola
spring.jpa.show-sql=true

# Tamaño máximo de imagen que se puede subir
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB